version: "3.7"

services:

  database:
    ports:
      - "5432"
    environment:
      POSTGRES_DB: bereikbaarheid
      POSTGRES_USER: bereikbaarheid
      POSTGRES_PASSWORD: insecure
    build:
      dockerfile: Dockerfile_pgrouting
#    image: ghcr.io/amsterdam/bereikbaarheid-db:latest  # TODO: Uncomment when Jenkins is no longer used
    networks:
      - backend

  app: &app
    build:
      context: .
      target: app

    image: docker-registry.data.amsterdam.nl/datapunt/bereikbaarheid-backend-django:${VERSION:-latest}
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./deploy:/deploy
    depends_on:
      - database
    entrypoint: /app/deploy/wait-for-it.sh database:5432 --

  dev:
    <<: *app
    build:
      target: dev
    environment:
      - DEBUG=true
      - SECRET_KEY=123456
      - DJANGO_SETTINGS_MODULE=main.settings
      - DATABASE_NAME=bereikbaarheid
      - DATABASE_USER=bereikbaarheid
      - DATABASE_PASSWORD=insecure
    command:
      python manage.py runserver 0.0.0.0:8000
    networks:
      - backend

  test:
    <<: *app
    build:
      target: tests
#    image: ghcr.io/amsterdam/bereikbaarheid:latest  # TODO: Uncomment when Jenkins is no longer used
    environment:
      - DEBUG=true
      - SECRET_KEY=123456
      - DJANGO_SETTINGS_MODULE=main.settings
      - DATABASE_NAME=bereikbaarheid
      - DATABASE_USER=bereikbaarheid
      - DATABASE_PASSWORD=insecure
    command:
      pytest
    networks:
      - backend

networks:
  backend:
    name: amsterdam-bereikbaarheid
