apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: main
          image: 127.0.0.1:5001/bereikbaarheid-db:latest
          imagePullPolicy: Always # IfNotPresent
          env:
            - name: POSTGRES_DB
              value: bereikbaarheid
            - name: POSTGRES_USER
              value: bereikbaarheid
            - name: POSTGRES_PASSWORD
              value: insecure
            - name: PGDATA
              value: /data

          volumeMounts:
            - mountPath: "/data"
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
