image:
  registry: saks01weuacrpgpgo5qvmwo.azurecr.io
  repository: opdrachten/bereikbaarheid-backend-django
  tag: latest

labels:
  app: bereikbaarheid-backend

network:
  allow-ingress:
    selector: app == 'bereikbaarheid-backend'
    ingress:
      - action: Allow
    egress:
      - action: Allow

deployments:
  api:
    selectorLabels:
      component: api
    tempDirs:
      - /tmp
    resources:
      requests:
        cpu: 100m
        memory: "128Mi"
      limits:
        cpu: 200m
        memory: "256Mi"
    autoscale:
      cpu: 80
    containers:
      - name: api
        env:
          BASE_URL: /api
          ADMIN_ENABLED: false
        secrets:
          - vault
          - database
        ports:
          - port: 8000
            name: http
  admin:
    selectorLabels:
      component: admin
    tempDirs:
      - /tmp
    resources:
      requests:
        cpu: 100m
        memory: "128Mi"
      limits:
        cpu: 200m
        memory: "256Mi"
    containers:
      - name: admin
        env:
          BASE_URL: /admin
          ADMIN_ENABLED: true
          ADMIN_PATH: /
        secrets:
          - vault
          - database
        ports:
          - port: 8000
            name: http

jobs:
  migrate:
    annotations:
      helm.sh/hook: post-install,post-upgrade
      helm.sh/hook-weight: "-5"
    tempDirs:
      - /tmp
    resources:
      requests:
        cpu: 200m
        memory: "256Mi"
      limits:
        cpu: 500m
        memory: "512Mi"
    containers:
      - name: main
        secrets:
          - database
          - vault
        command:
          - python
          - manage.py
          - migrate

  certificate-init:
    secrets:
      - certificate
    annotations:
      helm.sh/hook: post-install,post-upgrade
    containers:
      - name: main
        command:
          - sleep
        args:
          - "1"

services:
  api:
    ports:
      - name: http
        port: 80
        targetPort: 8000
    selector:
      component: api
  admin:
    ports:
      - name: http
        port: 80
        targetPort: 8000
    selector:
      component: admin

ingress:
  external:
    className: nginx-external
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /api(/|$)(.*)
        service: api
        port: 80
    tls: certificate
  internal:
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /api(/|$)(.*)
        service: api
        port: 80
      - path: /admin(/|$)(.*)
        service: admin
        port: 80
    tls: certificate
  internal-motiv:
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    paths:
      - path: /api(/|$)(.*)
        service: api
        port: 80
      - path: /admin(/|$)(.*)
        service: admin
        port: 80
    tls: certificate

secrets:
  certificate:
    type: keyvault
    tls: bereikbaarheid

  vault:
    type: keyvault
    annotations:
      helm.sh/hook-weight: "-5"
    secrets:
      - secret-key
      - oidc-base-url
      - oidc-rp-client-id
      - oidc-rp-client-secret
      - applicationinsights-connection-string
