# Generated by Django 4.1.13 on 2023-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0007_alter_lastbeperking_lastbeperking_in_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venstertijdweg",
            name="verkeersbord",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
