# Generated by Django 4.1.13 on 2023-11-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0007_alter_lastbeperking_lastbeperking_in_kg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venstertijdweg",
            name="verkeersbord",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
