# Generated by Django 4.1.13 on 2023-11-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0008_alter_venstertijdweg_verkeersbord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venstertijdweg",
            name="verkeersbord",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
