# Generated by Django 5.0.6 on 2024-06-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bereikbaarheid", "0009_createcachetable"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Stremming",
        ),
    ]
