# Generated by Django 5.0.6 on 2024-09-11 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bereikbaarheid", "0010_delete_stremming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venstertijdweg",
            name="e_type",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[!@#$^*+.=;|].*",
                        inverse_match=True,
                        message="Specialcharacters like !@#$^*+.=;| are not allowed, remove and try again",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="venstertijdweg",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "[!@#$^*+.=;|].*",
                        inverse_match=True,
                        message="Specialcharacters like !@#$^*+.=;| are not allowed, remove and try again",
                    )
                ],
            ),
        ),
    ]
