resources:
  - ../../base

components:
  - ../../components/api
  - ../../components/database

commonLabels:
  team: opdrachten
  app: bereikbaarheid-api
  env: local

buildMetadata:
  - originAnnotations

patchesStrategicMerge:
  - deployment.yaml
  - migrate.job.yaml

secretGenerator:
  - name: app-secrets
    literals:
      - DEBUG=true
      - SECRET_KEY=dev
      - DATABASE_NAME=bereikbaarheid
      - DATABASE_USER=bereikbaarheid
      - DATABASE_PASSWORD=insecure
      - DATABASE_PORT=5432

images:
  - name: 127.0.0.1:5001/bereikbaarheid/api-dev
    newTag: latest
