host: localhost

image:
  imagePullPolicy: Always

jobs:
  certificate-init:
    enabled: false

ingress:
  app:
    tls: null

secrets:
  certificate:
    enabled: false

  database:
    type: opaque
    secrets:
      database-host: database
      database-name: bereikbaarheid
      database-user: bereikbaarheid

network:
  allow-ingress:
    enabled: false