host: localhost

image:
  imagePullPolicy: Always

jobs:
  certificate-init:
    enabled: false

persistentVolumeClaims:
  data:
    resources:
      requests:
        storage: 1Gi

deployments:
  database:
    labels:
      component: database
    image:
      registry: null
      repository: postgis/postgis
      tag: 14-3.3
    securityContext:
      runAsNonRoot: false
      runAsUser: null
    env:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - name: data
        persistentVolumeClaim: data
    containers:
      - name: main
        securityContext:
          readOnlyRootFilesystem: false
        volumes:
          - name: data
            mountPath: /data

services:
  database:
    selector:
      component: database
    ports:
      - port: 5432
        targetPort: 5432

secrets:
  certificate:
    enabled: false

  database:
    type: opaque
    secrets:
      database-host: database-backend
      database-name: dev
      database-user: dev
      database-password: dev
      debug: "true"

  vault:
    type: opaque
    secrets:
      secret-key: 'dev'
      oidc-base-url: ''
      oidc-rp-client-id: ''
      oidc-rp-client-secret: ''
      applicationinsights-connection-string: ''

network:
  allow-ingress:
    enabled: false

ingress:
  external:
    enabled: false
    className: nginx
    tls: null
  internal:
    className: nginx
    tls: null
