# Generated by Django 4.1.13 on 2023-11-20 16:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bericht",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.BigAutoField(help_text="Id", primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                ("advice", models.TextField(blank=True, null=True)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("body_en", models.TextField(blank=True, null=True)),
                ("advice_en", models.TextField(blank=True, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("body_fr", models.TextField(blank=True, null=True)),
                ("advice_fr", models.TextField(blank=True, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("body_de", models.TextField(blank=True, null=True)),
                ("advice_de", models.TextField(blank=True, null=True)),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("body_es", models.TextField(blank=True, null=True)),
                ("advice_es", models.TextField(blank=True, null=True)),
                ("startdate", models.DateField(help_text="Publicatie startdatum")),
                ("enddate", models.DateField(help_text="Publicatie einddatum")),
                ("category", models.CharField(blank=True, max_length=55, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("image_url", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "important",
                    models.BooleanField(help_text="Belangrijk bericht (Komt bovenaan de lijst te staan)"),
                ),
                ("is_live", models.BooleanField(help_text="Publiceren op Tour Buzz")),
                ("lat", models.FloatField(blank=True, help_text="Latitude", null=True)),
                (
                    "lon",
                    models.FloatField(blank=True, help_text="Longitude", null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        default="SRID=28992;POINT(122025.80 488234.44)", srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "Bericht",
                "verbose_name_plural": "Berichten",
            },
        ),
    ]
