# Generated by Django 4.2.7 on 2023-11-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touringcar", "0002_alter_bericht_geometry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bericht",
            name="advice_de",
            field=models.TextField(blank=True, help_text="duits", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_en",
            field=models.TextField(blank=True, help_text="engels", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_es",
            field=models.TextField(blank=True, help_text="spaans", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_fr",
            field=models.TextField(blank=True, help_text="frans", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_de",
            field=models.TextField(blank=True, help_text="duits", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_en",
            field=models.TextField(blank=True, help_text="engels", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_es",
            field=models.TextField(blank=True, help_text="spaans", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_fr",
            field=models.TextField(blank=True, help_text="frans", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="is_live",
            field=models.BooleanField(default=True, help_text="Publiceren op Tour Buzz"),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_de",
            field=models.CharField(blank=True, help_text="duits", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_en",
            field=models.CharField(blank=True, help_text="engels", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_es",
            field=models.CharField(blank=True, help_text="spaans", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_fr",
            field=models.CharField(blank=True, help_text="frans", max_length=255, null=True),
        ),
    ]
