# Generated by Django 4.2.7 on 2023-12-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touringcar", "0003_alter_bericht_advice_de_alter_bericht_advice_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bericht",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="touringcar"),
        ),
    ]
