# Generated by Django 5.0.1 on 2024-02-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("touringcar", "0005_alter_bericht_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bericht",
            name="advice",
            field=models.TextField(blank=True, help_text="advies", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_de",
            field=models.TextField(blank=True, help_text="duits: advies", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_en",
            field=models.TextField(blank=True, help_text="engels: advies", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_es",
            field=models.TextField(blank=True, help_text="spaans: advies", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="advice_fr",
            field=models.TextField(blank=True, help_text="frans: advies", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body",
            field=models.TextField(blank=True, help_text="onderwerp", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_de",
            field=models.TextField(blank=True, help_text="duits: onderwerp", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_en",
            field=models.TextField(
                blank=True, help_text="engels: onderwerp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_es",
            field=models.TextField(
                blank=True, help_text="spaans: onderwerp", null=True
            ),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="body_fr",
            field=models.TextField(blank=True, help_text="frans: onderwerp", null=True),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title",
            field=models.CharField(help_text="titel", max_length=255),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_de",
            field=models.CharField(
                blank=True, help_text="duits: titel", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_en",
            field=models.CharField(
                blank=True, help_text="engels: titel", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_es",
            field=models.CharField(
                blank=True, help_text="spaans: titel", max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bericht",
            name="title_fr",
            field=models.CharField(
                blank=True, help_text="frans: titel", max_length=255, null=True
            ),
        ),
    ]
