# Generated by Django 5.0.2 on 2024-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("touringcar", "0006_alter_bericht_advice_alter_bericht_advice_de_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bericht",
            name="image_url",
            field=models.ImageField(blank=True, null=True, upload_to="touringcar-images"),
        ),
    ]
