# Generated by Django 5.0.6 on 2024-09-18 11:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("touringcar", "0008_halte"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parkeerplaats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(help_text="omschrijving", max_length=50)),
                ("lat", models.FloatField(blank=True, help_text="Latitude", null=True)),
                (
                    "lon",
                    models.FloatField(blank=True, help_text="Longitude", null=True),
                ),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.PointField(
                        default="SRID=28992;POINT (122025.8 488234.44)", srid=28992
                    ),
                ),
                ("code", models.IntegerField(blank=True)),
                (
                    "location",
                    models.CharField(help_text="bijzonderheden", max_length=200),
                ),
                ("capacity", models.IntegerField(help_text="plaatsen")),
                (
                    "info",
                    models.CharField(
                        blank=True,
                        help_text="meerInformatie",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
