name: CI Checks

on:
  pull_request:
    branches: main
    
permissions: write-all

jobs:
  linting-and-tests:
    name: Templates
    uses: amsterdam/github-workflows/.github/workflows/CI.yml@v1
    with:
      check_linting: true
